require("./theme/js/jquery-3.1.1.min.js");
require("./theme/js/flickity.min.js");
// require("./theme/js/easypiechart.min.js");
// require("./theme/js/parallax.js");
require("./theme/js/typed.min.js");
// require("./theme/js/datepicker.js");
// require("./theme/js/isotope.min.js");
// require("./theme/js/ytplayer.min.js");
// require("./theme/js/lightbox.min.js");
require("./theme/js/granim.min.js");
// require("./theme/js/jquery.steps.min.js");
require("./theme/js/countdown.min.js");
// require("./theme/js/twitterfetcher.min.js");
// require("./theme/js/spectragram.min.js");
require("./theme/js/smooth-scroll.min.js");
require("./theme/js/scripts.js");
require("./cssBundel.js");
require("./js/contactus.js");
require("./js/lazysizes.min.js");
