require("./theme/css/bootstrap.css");
require("./theme/css/stack-interface.css");
require("./theme/css/socicon.css");
// require("./theme/css/lightbox.min.css");
require("./theme/css/flickity.css");
require("./theme/css/iconsmind.css");
// require("./theme/css/jquery.steps.css");
require("./theme/css/theme.css");
require("./css/custom.css");
require("./css/pages.css");
require("./theme/css/font-rubiklato.css");
